language: python
python:
  - 3.5
branches:
  only:
    - master
    - develop

# command to install dependencies
install:
  - pip install -r requirements.txt
  # - pip install coveralls
# command to run tests
script: pytest
# after_success:
#   - coveralls
